state:
  config_path: config.dev.yaml
server:
  host: 0.0.0.0
  port: 2665
files_path: 
  uploaded: D:\a_source\test\uploaded
  log: D:\a_source\test\log
  temp: D:\a_source\test\temp
# 加密key jwt
security:
  # 加密算法
  algorithm: HS256
  # 加密密钥
  secret: 1111111
  # 加密过期时间miniutes
  expire: 30
database:
  # 关系数据库 带postgis插件
  # postgresql:
    # host: 127.0.0.1
    # port: 5432
    # user: root
    # password: root
    # database: test
  # 嵌入式关系数据库
  # sqlite:
    # path: ./data.db
    # name: test
  # 图数据库
  neo4j:
    host: 127.0.0.1
    port: 7687
    user: neo4j
    password: 1111111
    database: neo4j
  # 嵌入式图数据库
  # kuzu:
    # host: 127.0.0.1
    # port: 5432
    # user: root
    # password: root
    # database: test
ai:
  openai:
    api_key: 1111111
    chat_model: gpt-4o
    embedding_model: text-embedding-3-large
    chat_url: https://api.openai.com/v1/chat/completions
    embedding_url: https://api.openai.com/v1/embeddings
  